version: '3.7'

services:
  app:
    build:
      context: .
    environment:
      - APP_MODULE=Sharing_Settings.asgi:application
      - DJANGO_SETTINGS_MODULE=Sharing_Settings.settings.prod
      - CHANNELS_REDIS_HOST=redis
      - CHANNELS_REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379
      - DB_NAME=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
