# Generated by Django 3.1.6 on 2021-02-04 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sended_files', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload_app.createfiles')),
                ('sended_users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
