# Generated by Django 3.1.6 on 2021-02-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderfiles',
            name='comment_activate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
