# Generated by Django 3.1.6 on 2021-02-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createfiles',
            name='create_date',
        ),
        migrations.AddField(
            model_name='createfiles',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True),
        ),
    ]
