# Generated by Django 3.1.6 on 2021-02-04 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload_app', '0002_senderfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderfiles',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
