# Generated by Django 3.1.6 on 2021-02-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0002_auto_20210204_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createfiles',
            name='date',
        ),
        migrations.AddField(
            model_name='createfiles',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
