# Generated by Django 3.1.6 on 2021-02-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0004_auto_20210204_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createfiles',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
