# Generated by Django 3.1.6 on 2021-02-04 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0004_auto_20210204_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('sender_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload_app.senderfiles')),
            ],
        ),
    ]
